services:
  postgresql:
    image: postgres:12
    container_name: basic-postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
    # string connection -> postgresql://postgres:postgres@localhost:5432/postgres